### PR TITLE
fix: Fix type error in send_color_temperature

### PR DESCRIPTION
**Pull request by eljek**

### CODE REVIEW

**Comment by Erriez** [comment]
@eljek  Thanks for your PR. Some questions:
  
I assume you've upgraded the project with the `2to3` tool? Which Python3 version are you using?
  
Is this related to https://github.com/Erriez/milight_ibox2_control_python/issues/1?

**Comment by eljek** [comment]
Hi!

Thank you for the nice implementation, that saved me a lot of time!

I used python 3.7, I did not use any conversion tool, just fixed this one print statement to get it to work with python 3. 

It is not related to #1, just to some issues that I experienced while using the code. The seq num issue caused a crash in my code, when issuing more than 255 commands in a row, this is working now.

Best regards

**Comment by Erriez** [comment]
Good to hear that this project is useful for you. I started the project years ago on Python2 which is now deprecated. A conversion tool `2to3` has been created for smooth upgrade to Python3. I've executed this and discovered a lot more changes on all `print` calls, renamed assertion calls and `raw_input() -> input()`.

I'll create a separate PR for this and a second one with your suggested changes. Can you test it afterwards? I think you have a different light device, so I can't test all combinations.

Thanks for your contribution!

**Comment by eljek** [comment]
Sure, that sounds good, I will test it with my device then!

**Comment by Erriez** [comment]
@eljek Can you test the functionality with `master`? This includes Python3 upgrade and your sequence number / color temperature overflow fixes and support for different `lamp_type`. Thanks!

**Pull request closed without merging**
